name: Your New Jekyll Site
markdown: redcarpet
pygments: true
port: 4000
safe: true
server: true
exclude: [".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
